[theme]
primaryColor = "#0f766e"
backgroundColor = "#f8fbff"
secondaryBackgroundColor = "#eaf4f1"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
